# This file was generated by Spago2Nix

{ pkgs ? import ./packages.nix {} }:

let
  inputs = {

    "aff" = pkgs.stdenv.mkDerivation {
        name = "aff";
        version = "v5.1.1";
        src = pkgs.fetchgit {
          url = "https://github.com/slamdata/purescript-aff.git";
          rev = "390857f9143e1a52f7403d05b14c9ca79d356737";
          sha256 = "19v5psd6jz13gr5yqyx8286b5bpfq1dax51w906y0mqgnfz92yzr";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "aff-bus" = pkgs.stdenv.mkDerivation {
        name = "aff-bus";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/slamdata/purescript-aff-bus.git";
          rev = "5f60dc3b29b6a37f08eacd210c979dbdfbc8ed76";
          sha256 = "17y6gcd8y6sibfkdijl9w0g4vwia0b005nc8jbyhp4svgszcv11x";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "affjax" = pkgs.stdenv.mkDerivation {
        name = "affjax";
        version = "v9.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/slamdata/purescript-affjax.git";
          rev = "ec9c50e35980ba33b4bc7a3bc026970ba27bf767";
          sha256 = "04xij3q4802z58mzaaz661ifv1rd673fq2mjqj553dw326zplpvs";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "ansi" = pkgs.stdenv.mkDerivation {
        name = "ansi";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/hdgarrood/purescript-ansi.git";
          rev = "e060b4a7c9a0df9359871cb0c5773139e5525d2f";
          sha256 = "16kgy9zbdms9appd69gad2bka44ijkcnc9p0kf5g7x672jypx3ar";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "argonaut" = pkgs.stdenv.mkDerivation {
        name = "argonaut";
        version = "v6.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-argonaut.git";
          rev = "3365736b862ec6d8948ea31debebd04d0abf12fc";
          sha256 = "0b2jy5sf2lnn1r4kxnnm2vsr5iqkfas0jqp9yrrjmg7qngkd6qkw";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "argonaut-codecs" = pkgs.stdenv.mkDerivation {
        name = "argonaut-codecs";
        version = "v6.0.2";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-argonaut-codecs.git";
          rev = "b0317d576e10aa73600c43f835bfad45679d0aff";
          sha256 = "1i8dm95kbcl7k92jqnylhng1rjcqx5z12yhf6mwvp0z0bmsz250b";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "argonaut-core" = pkgs.stdenv.mkDerivation {
        name = "argonaut-core";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-argonaut-core.git";
          rev = "bebd7099b9cd681659dcd93407e639219360188e";
          sha256 = "1d3jgyap3vwc7mc01ji6brmd2n8lr9mmgx0fl88yalrm2j89jrcc";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "argonaut-traversals" = pkgs.stdenv.mkDerivation {
        name = "argonaut-traversals";
        version = "v7.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-argonaut-traversals.git";
          rev = "6613254947961686341eaa1ed23886c9d2587d93";
          sha256 = "0mr6c7c64c5b7ia0b68vsjyjxw06ac9908xpgxdd969kpvcwq9x3";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "arraybuffer-types" = pkgs.stdenv.mkDerivation {
        name = "arraybuffer-types";
        version = "v2.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-arraybuffer-types.git";
          rev = "505aa3de50a1400e5f2fce4a8e7b1a39abaa8fd9";
          sha256 = "059a8n49yhl46l1b1j2qj4ichzq6dzj29ajkfvw88npzj5w2rshy";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "arrays" = pkgs.stdenv.mkDerivation {
        name = "arrays";
        version = "v5.3.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-arrays.git";
          rev = "1bca4c0b8904e65d356ed6d8db8d6f7e071132d3";
          sha256 = "0r991qcx69xj07iagjaxkm0ab9qi2pw8cs3qwyybhis7asd6bnz6";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "avar" = pkgs.stdenv.mkDerivation {
        name = "avar";
        version = "v3.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/slamdata/purescript-avar.git";
          rev = "17914413130490318a475e9de6a9244aaaa097d2";
          sha256 = "14g05jm2xricy5b9vn4k4lhc9lzi5jvpvv85h10s17kn4wwi9igk";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "b64" = pkgs.stdenv.mkDerivation {
        name = "b64";
        version = "v0.0.5";
        src = pkgs.fetchgit {
          url = "https://github.com/menelaos/purescript-b64.git";
          rev = "114d33a1cc4e78815e6725a76e63cf6d0c113577";
          sha256 = "1rxspyslsyvqnv11i1yg6vrdjlvn0f2kynmm0h8443q3ig82m5r9";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "bifunctors" = pkgs.stdenv.mkDerivation {
        name = "bifunctors";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-bifunctors.git";
          rev = "1062425892b4a1c734ec653dded22546e3063b27";
          sha256 = "1bdra5fbkraglqrrm484vw8h0wwk48kzkn586v4y7fg106q1q386";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "catenable-lists" = pkgs.stdenv.mkDerivation {
        name = "catenable-lists";
        version = "v5.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-catenable-lists.git";
          rev = "d81b7df30d9879d0bb531b3102fb36f429c2f12e";
          sha256 = "0mbpb8xr9a7a4bvawhki7js5cbv7c0lv0vdwb6r8nmv6b61gzg27";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "colors" = pkgs.stdenv.mkDerivation {
        name = "colors";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/sharkdp/purescript-colors.git";
          rev = "fb582d3626e566371d20d4ef0b8d2795ee80f024";
          sha256 = "05bkfqllfpkh7nj0nzgd5p387hlpk0x35nam1i6xm3vzma9csj18";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "console" = pkgs.stdenv.mkDerivation {
        name = "console";
        version = "v4.2.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-console.git";
          rev = "add2bdb8a4af2213d993b728805f1f2a5e76deb8";
          sha256 = "1b2nykdq1dzaqyra5pi8cvvz4dsbbkg57a2c88yi931ynm19nnw6";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "const" = pkgs.stdenv.mkDerivation {
        name = "const";
        version = "v4.1.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-const.git";
          rev = "bc5db27b0ed3947fa5e2074ccbab01236eec3fa4";
          sha256 = "0qbd2aisax52yw6sybdhs7na943cbsd6mylhhgsamrf7hzh6v51p";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "contravariant" = pkgs.stdenv.mkDerivation {
        name = "contravariant";
        version = "v4.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-contravariant.git";
          rev = "cb69db0253c2e2ed3fef784dad58f3418a8ee834";
          sha256 = "0dd17lwlybpz4i54cxnqdgy38rjlbw9p7bw1r43is6z3kdc8983a";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "control" = pkgs.stdenv.mkDerivation {
        name = "control";
        version = "v4.1.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-control.git";
          rev = "8af53eea4ecc7b185776a0f144bcd7106ed08eb1";
          sha256 = "10703zvsnjm5fc74k6wzjsvpsfyc3jci3jxhm7rxf7ymya9z1z53";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "coroutines" = pkgs.stdenv.mkDerivation {
        name = "coroutines";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-coroutines.git";
          rev = "6f5750d1b200d6bb405f681f974887508b82b4d2";
          sha256 = "1jax7by8kn9fjg00avhziy3n18i3510iwzs3d73ziplanbw4qw4k";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "css" = pkgs.stdenv.mkDerivation {
        name = "css";
        version = "70ad3b95c070e79b1946aafc84cb446a17a3b695";
        src = pkgs.fetchgit {
          url = "https://github.com/slamdata/purescript-css";
          rev = "70ad3b95c070e79b1946aafc84cb446a17a3b695";
          sha256 = "04s9xl94z7mhgdf46mh92w0xpclg4w99kpjmzs6r261p07pmbhsj";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "datetime" = pkgs.stdenv.mkDerivation {
        name = "datetime";
        version = "v4.1.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-datetime.git";
          rev = "9e76abe96f45a68eb0bb23d0afd56031a8070bee";
          sha256 = "06ghfvbvd5sd0q014qi8j8glk2g2j9f8z8cwq2318kllp92gz07q";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "decimals" = pkgs.stdenv.mkDerivation {
        name = "decimals";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/sharkdp/purescript-decimals.git";
          rev = "4911f744fb7db6519758b6993edc28d0f81e0a89";
          sha256 = "1ad56xf8i7mwqlp718ik12dvc8aqwjxfpk7d8hdyjwzhf7b1ws2n";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "distributive" = pkgs.stdenv.mkDerivation {
        name = "distributive";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-distributive.git";
          rev = "3a43c0690883816e9ebeac510698423cfff5c174";
          sha256 = "0zbn0yq1vv7fbbf1lncg80irz0vg7wnw9b9wrzxhdzpbkw4jinsl";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "dom-filereader" = pkgs.stdenv.mkDerivation {
        name = "dom-filereader";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/nwolverson/purescript-dom-filereader.git";
          rev = "14ef7eb23c7b90113c3a9d0e745359a6efecbff1";
          sha256 = "0337r9qrnrgmfpssdvls5rz03y97kmxp2s8fr72i5hycih93yv74";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "dom-indexed" = pkgs.stdenv.mkDerivation {
        name = "dom-indexed";
        version = "v7.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/slamdata/purescript-dom-indexed.git";
          rev = "c449ae115bffe1fce89e145da62b862ad16ed935";
          sha256 = "18is75gsiix9w3f3lkly15cvs7ma1qc13hhi6wkl8nsj2g9g55ld";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "dotenv" = pkgs.stdenv.mkDerivation {
        name = "dotenv";
        version = "v1.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/nsaunders/purescript-dotenv.git";
          rev = "641fd4cdd48c30faea233c094f06e1b7ddb87c77";
          sha256 = "0dpjymzxz9wh6kll8q5qmx761pkp64y95dyyr4mwmj07k3anch3i";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "effect" = pkgs.stdenv.mkDerivation {
        name = "effect";
        version = "v2.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-effect.git";
          rev = "6caa8e1e162a21eed025613c2c19194b996ef779";
          sha256 = "1vqw5wrdxzh1ww6z7271xr4kg4mx0r3k3mwg18dmgmzj11wbn2wh";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "either" = pkgs.stdenv.mkDerivation {
        name = "either";
        version = "v4.1.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-either.git";
          rev = "8b4b38a729f8e88750b03e5c7baf2b3863ce4742";
          sha256 = "12j7vvjly0bgxidxmb2pflx0zy7x425dnvxk2y1pm66n0hbsq7ns";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "encoding" = pkgs.stdenv.mkDerivation {
        name = "encoding";
        version = "v0.0.5";
        src = pkgs.fetchgit {
          url = "https://github.com/menelaos/purescript-encoding.git";
          rev = "8a697897538ac8d0c7de66770bb83a98b0a662b9";
          sha256 = "1p52293hmqv3j3lra2fgamk5mpkalwp925frsl25w16n6gkx71p6";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "enums" = pkgs.stdenv.mkDerivation {
        name = "enums";
        version = "v4.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-enums.git";
          rev = "19800105b556798ea5650f8a01bfe5ea17cfc6eb";
          sha256 = "0qq0pgmq497nfml0y8xb2qdpga5xqp9sqq4ilv1rpyhg1v7nzb6v";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "exceptions" = pkgs.stdenv.mkDerivation {
        name = "exceptions";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-exceptions.git";
          rev = "9012eb08749e9ccd5da45bdece5d576e5fc0b0db";
          sha256 = "17s0rg9k4phivhx9j3l2vqqfdhk61gpj1xfqy8w6zj3rnxj0b2cv";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "exists" = pkgs.stdenv.mkDerivation {
        name = "exists";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-exists.git";
          rev = "ef53359aebc09bf863800ca86ad1dcd76f0b08ae";
          sha256 = "0bbdbw3jaqyi8dj2d52zvfgx4vl84d8cr6hp43vy8lfjfcbj0wlk";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "express" = pkgs.stdenv.mkDerivation {
        name = "express";
        version = "";
        src = pkgs.fetchgit {
          url = "https://github.com/nkly/purescript-express";
          rev = "b0d3d31703a02a7dddc48fa23669bebe6de85e90";
          sha256 = "095bby8i05cvzbh7kkhbnd4sc1dpvg5vrzh26gss3zpz8i786b2d";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "fixed-points" = pkgs.stdenv.mkDerivation {
        name = "fixed-points";
        version = "v5.1.0";
        src = pkgs.fetchgit {
          url = "https://github.com/slamdata/purescript-fixed-points.git";
          rev = "44ae7a7135bd17dc6d865d31f166a8cf5fa65c7e";
          sha256 = "14acfi7897z2vd8mq52h0gz8x31wyrvalb490rqjf4nyk73vhg36";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "foldable-traversable" = pkgs.stdenv.mkDerivation {
        name = "foldable-traversable";
        version = "v4.1.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-foldable-traversable.git";
          rev = "29d5b873cc86f17e0082d777629819a96bdbc7a1";
          sha256 = "03x89xcmphckzjlp4chc7swrpw347ll5bvr2yp7x9v2jqw2jlyi1";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "foreign" = pkgs.stdenv.mkDerivation {
        name = "foreign";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-foreign.git";
          rev = "3b8f3ae608db339ed5cff35d2017a07efb905b4d";
          sha256 = "15mz2s4f8crkd721z4df2aag4s0wil6fs07cpcmi7dpnkn7a4nab";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "foreign-generic" = pkgs.stdenv.mkDerivation {
        name = "foreign-generic";
        version = "v10.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/paf31/purescript-foreign-generic.git";
          rev = "46f09996bd54efc146bc1725783789dbac7d6a5b";
          sha256 = "1assvgmnim908plv7wzz4mrvq3lh4ayimgz5xk5njyz8p6pzkyvl";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "foreign-object" = pkgs.stdenv.mkDerivation {
        name = "foreign-object";
        version = "v2.0.3";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-foreign-object.git";
          rev = "8a7dc21c48e3e6d31e253b0e58dd95a3bbd7f6e7";
          sha256 = "07wiql59zfj901nk9526b6rykn9m24jjcs8v5dgxbr1c3hiab9n3";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "fork" = pkgs.stdenv.mkDerivation {
        name = "fork";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/slamdata/purescript-fork.git";
          rev = "27b9f223645a08b42731531a154892eaa263b590";
          sha256 = "1jygqzyci40c28gw2ygnx8v52hilhajj1bdpn7ndvss4i7yh1lcp";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "form-urlencoded" = pkgs.stdenv.mkDerivation {
        name = "form-urlencoded";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-form-urlencoded.git";
          rev = "acccb8ae3e38ffc5d2803d576bb6e409adee7195";
          sha256 = "1kl937qxnbn9m1bn0ijpnfiizgpcvcrnzqcc1scwq2kxvxh8kqap";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "formatters" = pkgs.stdenv.mkDerivation {
        name = "formatters";
        version = "v4.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/slamdata/purescript-formatters.git";
          rev = "c39ae1fef63a4c5ed6ccb9faf80e6b99922a369b";
          sha256 = "1i9dnh7xr6wmmgaphy75m9jdrg3qbjm3ml5fwg4ihy87x9w1fv1l";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "free" = pkgs.stdenv.mkDerivation {
        name = "free";
        version = "v5.2.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-free.git";
          rev = "f686f5fc07766f3ca9abc83b47b6ad3da326759a";
          sha256 = "1bwj0ay7q9lm4ir29jy549m05jvaqik1s615biv23y51ngx3fn49";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "freeap" = pkgs.stdenv.mkDerivation {
        name = "freeap";
        version = "v5.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/ethul/purescript-freeap.git";
          rev = "8f7bebc36c267794c31d5af1a5737746645e59df";
          sha256 = "007840vpxa4gz0fvjbahyky2xzz625gzfaiy2wjpb50d9qacsr7y";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "freet" = pkgs.stdenv.mkDerivation {
        name = "freet";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-freet.git";
          rev = "8b9cee0a143ec965eaa6e2d9ccfd24fd1f129bd7";
          sha256 = "1kpgggwimxjvdvhn6s7z4lzg3yw1rqg5f7pyamx9gh232s4va40i";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "functions" = pkgs.stdenv.mkDerivation {
        name = "functions";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-functions.git";
          rev = "c63451ae74f6fba7a4eede5f87208a73c537af77";
          sha256 = "0675k5kxxwdvsjs6a3is8pwm3hmv0vbcza1b8ls10gymmfz3k3hj";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "functors" = pkgs.stdenv.mkDerivation {
        name = "functors";
        version = "v3.1.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-functors.git";
          rev = "96bcf8a970a40115a76a20d19e50aa3b524adcf3";
          sha256 = "1cnn3zhk6qcyiwbbpvrdqgsbch4qihx2y9d6sv45bvd8kzrbd306";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "gen" = pkgs.stdenv.mkDerivation {
        name = "gen";
        version = "v2.1.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-gen.git";
          rev = "36f36f03f082b57e402c27f1513f8935caa54101";
          sha256 = "0pk68cn1s89hql30ydks9gh34gbxg391smi2albx3qvxnfkrpxca";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "generics-rep" = pkgs.stdenv.mkDerivation {
        name = "generics-rep";
        version = "v6.1.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-generics-rep.git";
          rev = "aae27ba1de21dda342dcdfc8b3cc5b951bd5b3ec";
          sha256 = "15vchzbcvf6byks90q14lvcwb8hnxqzm2mrlxi7v1f7has4s74kn";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "globals" = pkgs.stdenv.mkDerivation {
        name = "globals";
        version = "v4.1.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-globals.git";
          rev = "8e6d69c36b6fd8c988a3664fc033ad11dbdd5860";
          sha256 = "03h4npdbsjr1mkjasdi071l0cl7zdf3l76a8f0x4ghx47yvpgadn";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "halogen" = pkgs.stdenv.mkDerivation {
        name = "halogen";
        version = "v5.0.0-rc.4";
        src = pkgs.fetchgit {
          url = "https://github.com/slamdata/purescript-halogen.git";
          rev = "01435825ece48016d2b1e0f16e50dfac81c1eb7a";
          sha256 = "0aba1a276cpq2ipxkvv551r6k0wbrq58sqffwfjx4pwmmrpcqi49";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "halogen-css" = pkgs.stdenv.mkDerivation {
        name = "halogen-css";
        version = "v8.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/slamdata/purescript-halogen-css.git";
          rev = "1600df2902eccc3e3c73559a3446c99469885af6";
          sha256 = "1a8sj8ydfnvj3vh2l3f0yyd69y7v4qki1a5m99n0v2aqc1y6nrzl";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "halogen-formless" = pkgs.stdenv.mkDerivation {
        name = "halogen-formless";
        version = "";
        src = pkgs.fetchgit {
          url = "https://github.com/thomashoneyman/purescript-halogen-formless.git";
          rev = "b42d54ec9a74be9b99d45aed273c68bac3fdbfda";
          sha256 = "0wa40z4gwvm3x0ms9ql7zmgixnyhv3n5gcpab9fvzg6q6kiqxczs";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "halogen-media" = pkgs.stdenv.mkDerivation {
        name = "halogen-media";
        version = "";
        src = pkgs.fetchgit {
          url = "https://github.com/naglalakk/purescript-halogen-media";
          rev = "1b9d1a7a963537dbcc672f2d154606752998ddf7";
          sha256 = "16amfqbcg58g4arn9m7snmnd7p95ckbz6j4dxby1h8lqr1qvz702";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "halogen-rawhtml" = pkgs.stdenv.mkDerivation {
        name = "halogen-rawhtml";
        version = "";
        src = pkgs.fetchgit {
          url = "https://github.com/naglalakk/purescript-halogen-rawhtml";
          rev = "2b38c6cfb71ebb1ab75bf3724886f70dd05de651";
          sha256 = "0zhgkvqv9xw5kd7jdpr0m4w2j2x8snhk7lggzrs942qkvxpjim7y";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "halogen-renderless" = pkgs.stdenv.mkDerivation {
        name = "halogen-renderless";
        version = "";
        src = pkgs.fetchgit {
          url = "https://github.com/thomashoneyman/purescript-halogen-renderless";
          rev = "83278eaa735001803a751a82472f2caa9c2c9c70";
          sha256 = "0fsg7sdhyb6in2pbxkzs71pd8mw5h7ni4himhmyhism6xxd47ilq";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "halogen-vdom" = pkgs.stdenv.mkDerivation {
        name = "halogen-vdom";
        version = "v6.1.0";
        src = pkgs.fetchgit {
          url = "https://github.com/slamdata/purescript-halogen-vdom.git";
          rev = "34c032aa5f72b600d69ab970e2737ca533c6c118";
          sha256 = "1zsivlk74zn6wkw25mvc12yjnqfjgyfpmhs3rsrvgycnmswdavnk";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "heterogeneous" = pkgs.stdenv.mkDerivation {
        name = "heterogeneous";
        version = "v0.4.1";
        src = pkgs.fetchgit {
          url = "https://github.com/natefaubion/purescript-heterogeneous.git";
          rev = "854e6fe8e52c570954c22275aaf657ef068c73f8";
          sha256 = "0kbp6k6nbqwyzf12lrgf1v18ln5rakmxzb8s2dha1lfnk1r2f92m";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "http-methods" = pkgs.stdenv.mkDerivation {
        name = "http-methods";
        version = "v4.0.2";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-http-methods.git";
          rev = "f3672edd166d323849b9dfd1e01c6eeb978fd56c";
          sha256 = "1wfgrlnl33bcqw54hbc8icah2fi0rvi5zxhz07665vy9p5ppvkqs";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "identity" = pkgs.stdenv.mkDerivation {
        name = "identity";
        version = "v4.1.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-identity.git";
          rev = "1b7938abdc8cb28c0ac5f80f63405d53e3173a8e";
          sha256 = "1scdgbfkphfmapw7p9rnsiynpmqzyvnal2glzj450q51f8g1dhld";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "integers" = pkgs.stdenv.mkDerivation {
        name = "integers";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-integers.git";
          rev = "3850da9cd96b37c71685b6bc3bf0cb489baefc93";
          sha256 = "17d4bfpnrmbxlc7hhhrvnli70ydaqyr26zgvc9q52a76zgdcb4cf";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "invariant" = pkgs.stdenv.mkDerivation {
        name = "invariant";
        version = "v4.1.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-invariant.git";
          rev = "b704c5bda262719ca5cc88a3f8554edff8f03256";
          sha256 = "1fimpbh3yb7clvqxcdf4yf9im64z0v2s9pbspfacgq5b4vshjas9";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "js-date" = pkgs.stdenv.mkDerivation {
        name = "js-date";
        version = "v6.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-js-date.git";
          rev = "f332c15f14322434ddd1945ca2db8040294447bf";
          sha256 = "19qyzbr4a1ca8znbd8gcbz0a801f5p1v238ky3408gdx4ba32zjd";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "js-timers" = pkgs.stdenv.mkDerivation {
        name = "js-timers";
        version = "v4.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-js-timers.git";
          rev = "8206d3d8034357b4665828e52f7ff1b8cb46611e";
          sha256 = "1a8092sli7zqw1wflibhjza1ww21dxl7x7r602iazzwh2g70v4dg";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "lazy" = pkgs.stdenv.mkDerivation {
        name = "lazy";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-lazy.git";
          rev = "5bbd04f507a704f39aa756b5e12ed6665205fe2e";
          sha256 = "156q89l4nvvn14imbhp6xvvm82q7kqh1pyndmldmnkhiqyr84vqv";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "lcg" = pkgs.stdenv.mkDerivation {
        name = "lcg";
        version = "v2.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-lcg.git";
          rev = "596bcb17bd550397735220f919df52bcd0038fe0";
          sha256 = "1851cq2g84jzjbvbmncbivbhaqzj9zv5ni3gs14k04nmx2brxmvj";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "lists" = pkgs.stdenv.mkDerivation {
        name = "lists";
        version = "v5.4.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-lists.git";
          rev = "62900a56f6864638c952575dfd211a1cc55be7da";
          sha256 = "0l0jiqhcjzkg4nv2a6h2vdf4izr9mf7cxc86cq1hf3j4dh6spym1";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "math" = pkgs.stdenv.mkDerivation {
        name = "math";
        version = "v2.1.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-math.git";
          rev = "8be36d24f9d2d8795adf04791446bbc458297b9b";
          sha256 = "1msmy9w7y6fij62sdc55w68gpwkhm6lhgc8qjisjk4sxx1wdg1rr";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "maybe" = pkgs.stdenv.mkDerivation {
        name = "maybe";
        version = "v4.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-maybe.git";
          rev = "81f0397636bcbca28642f62421aebfd9e1afa7fb";
          sha256 = "073wa0d51daxdwacfcxg5pf6ch63n4ii55xm1ih87bxrg8mp52mx";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "media-types" = pkgs.stdenv.mkDerivation {
        name = "media-types";
        version = "v4.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-media-types.git";
          rev = "e304498356539547b4ed9a7f79513a847c907962";
          sha256 = "0ykwmxrhmwfy6c5mxjxa43xdf5xqakrqyvr5fn986yad50gjqj75";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "mmorph" = pkgs.stdenv.mkDerivation {
        name = "mmorph";
        version = "v5.1.0";
        src = pkgs.fetchgit {
          url = "https://github.com/Thimoteus/purescript-mmorph.git";
          rev = "e067ee63c9c08e67b632a8b55930f744ddfad980";
          sha256 = "1lvdclqi9wzs4j8xj8ygnj2b87hhpbnl0c6m28zac05rz87s09mg";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "newtype" = pkgs.stdenv.mkDerivation {
        name = "newtype";
        version = "v3.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-newtype.git";
          rev = "7d85fa6a040208c010b05f7c23af6a943ba08763";
          sha256 = "0qvk9p41miy806b05b4ikbr3if0fcyc35gfrwd2mflcxxp46011c";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "node-buffer" = pkgs.stdenv.mkDerivation {
        name = "node-buffer";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-node/purescript-node-buffer.git";
          rev = "d279daa1b4bf9fe85d5c3aeb96512df4f12e0bc0";
          sha256 = "0ih2y29srdxgn526fw2v1y95hpivjil44vkl93w6nrqsymki36y0";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "node-child-process" = pkgs.stdenv.mkDerivation {
        name = "node-child-process";
        version = "v6.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-node/purescript-node-child-process.git";
          rev = "887b252ef85975f4cf31dfd9079f6d98d905fc1b";
          sha256 = "1r5gx9gr5xkrbvdnv6704zmpb987dgpblmhq5yhwq2xir6w35qnn";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "node-fs" = pkgs.stdenv.mkDerivation {
        name = "node-fs";
        version = "v5.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-node/purescript-node-fs.git";
          rev = "02d610f237dc130edb5ee594fd46b16c691b79eb";
          sha256 = "0i3bd7aw16vyb5sh5fzlvgg9q6cjdvmnfs57in6rxm34z8d8c0p8";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "node-fs-aff" = pkgs.stdenv.mkDerivation {
        name = "node-fs-aff";
        version = "v6.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-node/purescript-node-fs-aff.git";
          rev = "d02c0a209824c3fce8254dddd94d85990e9ad1b6";
          sha256 = "0vjc9zag7y20yxhhv45hrwv9fbpmp0szv40vaxl5x8mnd5wv28x7";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "node-http" = pkgs.stdenv.mkDerivation {
        name = "node-http";
        version = "v5.0.2";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-node/purescript-node-http.git";
          rev = "b18d054de436ad589d41acee0aca7f3bd6762aab";
          sha256 = "0jr9mm0kdvkd3nf1g4l8w9p7n16qqji03fg1agxn7hngr4ja43pw";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "node-path" = pkgs.stdenv.mkDerivation {
        name = "node-path";
        version = "v3.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-node/purescript-node-path.git";
          rev = "e3a704d5fc7d25fa93c6cd0eb92dbce9e5ebd69a";
          sha256 = "0j1ni52m62dpcrfakl1ik131i31bkg91yv0p1c40sdw0f59fzf6x";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "node-process" = pkgs.stdenv.mkDerivation {
        name = "node-process";
        version = "v7.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-node/purescript-node-process.git";
          rev = "88871d84a69f47dd2d1d9eccd7cc942be4457d46";
          sha256 = "1sbhpz3d3r6z12cx1k7rb6nycxf9cyc61zdx6mvk2q2lmzfdm1if";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "node-streams" = pkgs.stdenv.mkDerivation {
        name = "node-streams";
        version = "v4.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-node/purescript-node-streams.git";
          rev = "88740eeda2017d3ddcde50eea59d57c7749d8524";
          sha256 = "12dki2li0d7s54kvcr6gksb5nxf6kzs93gwxnq4bh1flri8p0i7r";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "node-url" = pkgs.stdenv.mkDerivation {
        name = "node-url";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-node/purescript-node-url.git";
          rev = "20eecd603124bf07b477f1f2be2135ae99c885fe";
          sha256 = "0qbpdz62psy7hb34hw5rw2x1pq7yhd214ysza0xh46c3nlp0ib9y";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "nonempty" = pkgs.stdenv.mkDerivation {
        name = "nonempty";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-nonempty.git";
          rev = "36ca3b2fa6d98b1c9d2ee05643341e496fbeab57";
          sha256 = "1vz174sg32cqrp52nwb2vz9frrzmdwzzlgl4vc2cm5wlf2anirxj";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "now" = pkgs.stdenv.mkDerivation {
        name = "now";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-now.git";
          rev = "090feddf7c7dec2a812eca090cd211e87ccad606";
          sha256 = "18h5pif2dy4r7w1xg2zw4mvdqlar9xqp3rawkiavmsc946ncf3zs";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "nullable" = pkgs.stdenv.mkDerivation {
        name = "nullable";
        version = "v4.1.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-nullable.git";
          rev = "8d413f02224b8281bfa8037e45fbbf9fe2e254fd";
          sha256 = "14qaxxga8gqlr4pijyvqycdyhjr6qpz3h4aarficw5j75b7x8nyv";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "numbers" = pkgs.stdenv.mkDerivation {
        name = "numbers";
        version = "v7.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/sharkdp/purescript-numbers.git";
          rev = "6262a5f17dcdfba11dfae03f4fa8eec02f7ed29f";
          sha256 = "1l9s22fkjf7wc0zd3wjax4hlif7gqh6ij0ijb8sq20mfh2xl4hj8";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "options" = pkgs.stdenv.mkDerivation {
        name = "options";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-options.git";
          rev = "bc0109fb1a18d5f51aa32914618e96d1ec9d8cf5";
          sha256 = "1n25pp0xsxfdxsnfdjjwlxz79iam9kapx4al9aj24yi148xhqckl";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "ordered-collections" = pkgs.stdenv.mkDerivation {
        name = "ordered-collections";
        version = "v1.6.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-ordered-collections.git";
          rev = "54af8b281bf01acfc14e147debec76974901e93c";
          sha256 = "0r48p94d3cyzni2z7ikzcap472k23dx8zq37c1prmjb01v03mfvc";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "orders" = pkgs.stdenv.mkDerivation {
        name = "orders";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-orders.git";
          rev = "80e22c22c72c846e09ef9dfcdb40b3eee39118d6";
          sha256 = "13p1sm4dxkmxhld9x5qqg62iiajjb3qpzs66c1r24y5fs4zsfry4";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "parallel" = pkgs.stdenv.mkDerivation {
        name = "parallel";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-parallel.git";
          rev = "4d6c8b05041a36c300dfca2ba8f1f3443ca26bc6";
          sha256 = "1d5bnagabw2k8yxywkygwrpblb2ggqh2fhpqfrx2sj1y53x332hg";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "parsing" = pkgs.stdenv.mkDerivation {
        name = "parsing";
        version = "v5.0.3";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-parsing.git";
          rev = "e801a0ef42f3211b1602a94a269eef7ce551423f";
          sha256 = "0m5xvb5kis28laj3navyyakyq408vw115c2dvngf1vljzh1hk5kj";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "partial" = pkgs.stdenv.mkDerivation {
        name = "partial";
        version = "v2.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-partial.git";
          rev = "76b63a324f7eafbb859256771b5bb7404082af96";
          sha256 = "11qr80989g7xmvw1brnrclsbg2wdkbr5k3cqpngfip3nnirrypcn";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "pipes" = pkgs.stdenv.mkDerivation {
        name = "pipes";
        version = "v6.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/felixSchl/purescript-pipes.git";
          rev = "a9533035f6fe8e59a65c6d11a3a7c767f3c9ae67";
          sha256 = "0vl37f42dy4w4hswiay22w0n14k7sr670x54iwn7428larzrzs8y";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "posix-types" = pkgs.stdenv.mkDerivation {
        name = "posix-types";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-node/purescript-posix-types.git";
          rev = "1d4cd274436cc1e470dc6bf7735bcfdf0092d884";
          sha256 = "0xvxjvxr7n4dv53p8w5qfmgx37cga5bp2rjhkbfvj89rb74vm3i1";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "precise-datetime" = pkgs.stdenv.mkDerivation {
        name = "precise-datetime";
        version = "";
        src = pkgs.fetchgit {
          url = "https://github.com/awakesecurity/purescript-precise-datetime";
          rev = "2355b3471b758e16d17078e09bb79ee26d82b90a";
          sha256 = "11c0nwavc6sn5d2795wclg43grqmzblhr7xvd7dzzya6ap6aw0v1";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "prelude" = pkgs.stdenv.mkDerivation {
        name = "prelude";
        version = "v4.1.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-prelude.git";
          rev = "a96663b34364fdd0885a200955e35b99f4e58c43";
          sha256 = "1frvjrv0mr508r6683l1mp5rzm1y2dz76fz40zf4k2c64sy6y1xm";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "profunctor" = pkgs.stdenv.mkDerivation {
        name = "profunctor";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-profunctor.git";
          rev = "1de584baf49624cc0d1686067d82b93523654c1b";
          sha256 = "1v4kvmhmiwznd4lswp9339h64pgv5zvd3vm1q7gzj70767a3941i";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "profunctor-lenses" = pkgs.stdenv.mkDerivation {
        name = "profunctor-lenses";
        version = "v6.2.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-profunctor-lenses.git";
          rev = "a058930ab7c73f5c4676a0cc91ea1a7433300c17";
          sha256 = "0bb8ib00in8d65kvympdlfncb7bp1qqsjvvpw9zfwiwf67ix4v57";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "proxy" = pkgs.stdenv.mkDerivation {
        name = "proxy";
        version = "v3.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-proxy.git";
          rev = "4a529b1f874fa2f32fc4c575cafaf46e0ab69fb6";
          sha256 = "0rqf25b1n9p5sgx7gdsxwrfv9rb3sqxgqmqpp5kdm30lfk7snz24";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "psci-support" = pkgs.stdenv.mkDerivation {
        name = "psci-support";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-psci-support.git";
          rev = "a66a0fa8661eb8b5fe75cc862f4e2df2835c058d";
          sha256 = "0jd773zcklr6hjddqingzmk20a0afpm2r9pczfjbj0d93pbxb4xh";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "quickcheck" = pkgs.stdenv.mkDerivation {
        name = "quickcheck";
        version = "v6.1.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-quickcheck.git";
          rev = "6289a80570acd5aec3ea89dc673cf10cdaf5794a";
          sha256 = "0b6208067krf81kzq2hbxs68386hcicbscwxbj5nck07ivjjvqh0";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "quill" = pkgs.stdenv.mkDerivation {
        name = "quill";
        version = "";
        src = pkgs.fetchgit {
          url = "https://github.com/naglalakk/purescript-quill";
          rev = "75812fefdebf67c24757890be1e9ddb6b40f90c9";
          sha256 = "1krg8ya5p5ai7d2cz5xql9b8389a8vaj2s387b2sw5f8x6yq8q2s";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "random" = pkgs.stdenv.mkDerivation {
        name = "random";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-random.git";
          rev = "75e6b21edbe0eec78c28ff3bd8265998f2ea0b45";
          sha256 = "0k37v7z529adx6ypxj0xjyfrz45qia6p0vki2wpvi8lik7c698gf";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "record" = pkgs.stdenv.mkDerivation {
        name = "record";
        version = "v2.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-record.git";
          rev = "42a15ba34d860f4d8f899836956bf09659a0256b";
          sha256 = "1l7ixb0gc2man36181g3hdf46sjp7xh0kv8bgrvalxfisjmd12v0";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "refs" = pkgs.stdenv.mkDerivation {
        name = "refs";
        version = "v4.1.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-refs.git";
          rev = "e8b175477661e433175e76548168290c40e0ce4b";
          sha256 = "08161iy1xbafzblv033v84156azpcqkiw9v9d6gliphrq5fm17gm";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "routing" = pkgs.stdenv.mkDerivation {
        name = "routing";
        version = "v9.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/slamdata/purescript-routing.git";
          rev = "62742c314b7a30118399f1b98fdec27212f8f40e";
          sha256 = "1q05k1nrwpmlwy35fwa6kp1drk1ywnf5srmm1rzpliprvpli3is7";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "routing-duplex" = pkgs.stdenv.mkDerivation {
        name = "routing-duplex";
        version = "";
        src = pkgs.fetchgit {
          url = "https://github.com/natefaubion/purescript-routing-duplex";
          rev = "eceaba4ee9921250cc6640d5ead98bbfc44310f5";
          sha256 = "0cpihagrbldymd108x9isxwrckac1h1mb3rrj224m1p5bgv83ixi";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "run" = pkgs.stdenv.mkDerivation {
        name = "run";
        version = "v3.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/natefaubion/purescript-run.git";
          rev = "68eec5b5957e6f36fc4e206a1d4dd2adc3095587";
          sha256 = "1lb95hxmmv3ndrxxwl1rwja8sply5na2bsgy1iym82cm96xcxib3";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "semirings" = pkgs.stdenv.mkDerivation {
        name = "semirings";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-semirings.git";
          rev = "36aedc601d296607439eec1e71f8483adc373ffc";
          sha256 = "0bhrhn2yvcgil7g63spb2xw966mdhlk9mpspnqfijdpb9n3b79ds";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "slug" = pkgs.stdenv.mkDerivation {
        name = "slug";
        version = "";
        src = pkgs.fetchgit {
          url = "https://github.com/thomashoneyman/purescript-slug";
          rev = "a97735d47be7398f181085e0b117499462ba7a11";
          sha256 = "07qpxr5lc9lfysif08mddqq2bnkvnxj9xhlrjzgl18g355hix7k1";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "spec" = pkgs.stdenv.mkDerivation {
        name = "spec";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-spec/purescript-spec.git";
          rev = "12bc11c4410dbd8060a6893fe5d07f350e4bb8ab";
          sha256 = "1b1hw3231ha5fq61948dfz28a0lm2mcn2pksszf7yw3137ysp5bn";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "st" = pkgs.stdenv.mkDerivation {
        name = "st";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-st.git";
          rev = "c1b9a0d47a5be1d7ea713ef1c583040eb332250a";
          sha256 = "0m2jkb9dmpbr8s1c20l7sm2q11y5rx8gqfiyspnyhq5apzkknjr0";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "strings" = pkgs.stdenv.mkDerivation {
        name = "strings";
        version = "v4.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-strings.git";
          rev = "94c843b93142d0edf1c31ec075c40b6984c3dc7b";
          sha256 = "147l3l3fzn7liparhm2y3p8j4ck1lblra5j493p2hy5yy5ndznc8";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "stringutils" = pkgs.stdenv.mkDerivation {
        name = "stringutils";
        version = "v0.0.9";
        src = pkgs.fetchgit {
          url = "https://github.com/menelaos/purescript-stringutils.git";
          rev = "7983cde4aa1edac2b31611eb7c1fd17abcff667c";
          sha256 = "00c679d5lk37gbfby2kasyq45rla6a0shg64zhyd2r4xrj0a74r4";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "sunde" = pkgs.stdenv.mkDerivation {
        name = "sunde";
        version = "v2.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/justinwoo/purescript-sunde.git";
          rev = "e9c898ac0ffd5e61d82a6c02606ab84241278709";
          sha256 = "051kfqc06fbhavd3anvfhi5wfj76a6q4piis4lplypaw9g4n64l2";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "tailrec" = pkgs.stdenv.mkDerivation {
        name = "tailrec";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-tailrec.git";
          rev = "69f4625969e313203028968e4a9f743fa7f87883";
          sha256 = "0z7k80nl8dgv8mc2w8xsl2n0637bd1l8ppxak8kaifgjjwa81hx3";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "test-unit" = pkgs.stdenv.mkDerivation {
        name = "test-unit";
        version = "v15.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/bodil/purescript-test-unit.git";
          rev = "351c55b632e0c0ebffae05837909995a03de3406";
          sha256 = "06lb90vppa7naqqwz7wbvlkkyz86pbdd3ycw3d2iygvxbzkz8xjn";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "these" = pkgs.stdenv.mkDerivation {
        name = "these";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-these.git";
          rev = "fc19af52b34f8f128f9981aa27aab4becd7a79d5";
          sha256 = "0ywwpbcz1d0pdi3f9h9kla52vq1if8zwdz7jq7lqz5s8zj8kyg5r";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "timestamp" = pkgs.stdenv.mkDerivation {
        name = "timestamp";
        version = "";
        src = pkgs.fetchgit {
          url = "https://github.com/naglalakk/purescript-timestamp";
          rev = "c308b43655ba1c100e53a15ce8146916c4b90e63";
          sha256 = "0i6l98g6c6xkwvb0sgx6hk681058nl3ibqh6h7fd53spyhx1r6b4";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "transformers" = pkgs.stdenv.mkDerivation {
        name = "transformers";
        version = "v4.2.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-transformers.git";
          rev = "0e473e5ef0e294615ca0d9aab0bcffee47b2870d";
          sha256 = "03qmvl9s7lbvm73dy9ps6qp39pdcm91hb8yakgj7aq8hgpj7b6bg";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "tuples" = pkgs.stdenv.mkDerivation {
        name = "tuples";
        version = "v5.1.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-tuples.git";
          rev = "0036bf9d99b721fd0f2e539d24e18e484b016927";
          sha256 = "045nsy0r2g51gih0wjhcvhl6gfr8947mlrqwg644ygz72rjm8wq4";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "type-equality" = pkgs.stdenv.mkDerivation {
        name = "type-equality";
        version = "v3.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-type-equality.git";
          rev = "2cdae51c394401cd5fc04b03c341273b41532b7d";
          sha256 = "1b7szyca5s96gaawvgwrw7fa8r7gqsdff7xhz3vvngnylv2scl3w";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "typelevel-prelude" = pkgs.stdenv.mkDerivation {
        name = "typelevel-prelude";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-typelevel-prelude.git";
          rev = "82b343fabfe3bf4ebf8106ce61bfe24fb3ed500c";
          sha256 = "01ki39xj87kwf8j8divlzwrvfyjcgxpmzhhmxzjylqx6jarcwyg6";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "unfoldable" = pkgs.stdenv.mkDerivation {
        name = "unfoldable";
        version = "v4.0.2";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-unfoldable.git";
          rev = "be3262a9dc48e794676b1b2883987331d4be6fd7";
          sha256 = "0lzhx030c5933maxcjwk6kzlvbxky1kiwrymqf1dp5wbrar3jyv4";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "unicode" = pkgs.stdenv.mkDerivation {
        name = "unicode";
        version = "v4.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-unicode.git";
          rev = "bb70f5a17aa9bcad05104c5a3f191fd75bb3d2ce";
          sha256 = "1a53jv7pzyjk5v6kmwwy50d3l8d26k0id59sn8g3lzkih24nalhp";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "unsafe-coerce" = pkgs.stdenv.mkDerivation {
        name = "unsafe-coerce";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-unsafe-coerce.git";
          rev = "fa6a5ca9b4581c00ee0b8539306a49badb7bee60";
          sha256 = "0k9255mk2mz6xjb11pwkgfcblmmyvr86ig5kr92jwy95xim09zip";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "unsafe-reference" = pkgs.stdenv.mkDerivation {
        name = "unsafe-reference";
        version = "v3.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-contrib/purescript-unsafe-reference";
          rev = "79d7de7b9351346a73e6c060d80532c95ba1c7c1";
          sha256 = "0q758dz59qz0li4s3w1qcg921xp5i5rh6i1l611iv7rr8cbj11al";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "uuid" = pkgs.stdenv.mkDerivation {
        name = "uuid";
        version = "v6.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/spicydonuts/purescript-uuid.git";
          rev = "6de5e57a8529eca6ac956103f6341c4fa7dfb25e";
          sha256 = "012sv8xngvyn65q28yl7n74rmspc9bn2g0dspl8wks4pn68ldvaq";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "validation" = pkgs.stdenv.mkDerivation {
        name = "validation";
        version = "v4.2.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-validation.git";
          rev = "bef3f9da737516e69f00d35310334004c29355cb";
          sha256 = "03irk6n7jgsimhp9ckrg2ns7qbc8d383ls3sslxgir5mr8xdc44g";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "variant" = pkgs.stdenv.mkDerivation {
        name = "variant";
        version = "v6.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/natefaubion/purescript-variant.git";
          rev = "31e620334124d2ca8b1e608c27d74b607a5831e9";
          sha256 = "0cn227q57zbqm6r1aw5kvnp1x8zkc1x7wx28yyz311lmy7k1mkql";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "web-clipboard" = pkgs.stdenv.mkDerivation {
        name = "web-clipboard";
        version = "v2.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-web/purescript-web-clipboard.git";
          rev = "5c4fe20111b9e37d74c805101b5c558928808971";
          sha256 = "17i7rpzxi7pgas32xz8vjcs54m94gnmca3my0p70gzvf3rasnxyx";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "web-dom" = pkgs.stdenv.mkDerivation {
        name = "web-dom";
        version = "v3.1.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-web/purescript-web-dom.git";
          rev = "dcfeb05905cedcdeeb88447259b022b6a1b824a4";
          sha256 = "05jp25zhp99ymgs1d6qhkyi13b1pdsk9rb9whvx8clja4i4g2365";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "web-events" = pkgs.stdenv.mkDerivation {
        name = "web-events";
        version = "v2.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-web/purescript-web-events.git";
          rev = "7f19f24d7b61066bef0813734964f2dc6b085e3d";
          sha256 = "1vd1gfh6zv50bq4v1ppl2wvc5mskcw9n1bfj29qjg0dx0ffxzv2f";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "web-file" = pkgs.stdenv.mkDerivation {
        name = "web-file";
        version = "v2.1.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-web/purescript-web-file.git";
          rev = "5245d62ba35357c6fb74fa919797d2b7c08110cd";
          sha256 = "08k0xv9zpg040v32k3wk66bhzx16c2nn9v35f01gq96anhm713s1";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "web-html" = pkgs.stdenv.mkDerivation {
        name = "web-html";
        version = "v2.2.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-web/purescript-web-html.git";
          rev = "6f0d367f737202fdf9638f1f6836716c26456014";
          sha256 = "026y4kkrc2z4zmxlc4z21znq8knaqqjazf1ny811gm1507b1ykc6";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "web-storage" = pkgs.stdenv.mkDerivation {
        name = "web-storage";
        version = "v3.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-web/purescript-web-storage.git";
          rev = "c2dedea1ee10ca7e94af5547c90274fb63ab3bc6";
          sha256 = "1ycb2s29aw9w6lqik6hfmp9nf9i2yhn0q26hc4p3450jam5mj8bx";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "web-touchevents" = pkgs.stdenv.mkDerivation {
        name = "web-touchevents";
        version = "v2.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-web/purescript-web-touchevents.git";
          rev = "cde8ea42d92035b1c46df4f1e1c38205aba7742a";
          sha256 = "0mhsfqlglx04q3vkjg4k33bkxcpx2cmbq4x1zxyhl48q1qqmnic8";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "web-uievents" = pkgs.stdenv.mkDerivation {
        name = "web-uievents";
        version = "v2.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-web/purescript-web-uievents.git";
          rev = "bdbc845bf8b06649c8361411085a0c0f788c9511";
          sha256 = "04032nl0z9hjq7b799zhbn7in10dz9kgrrcs0adjbaf08rc2kcwh";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "web-xhr" = pkgs.stdenv.mkDerivation {
        name = "web-xhr";
        version = "v3.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript-web/purescript-web-xhr.git";
          rev = "eb1db72a670b3b98877f33940dbe37097b722736";
          sha256 = "1217lmvla3rqd9kzvvjxpngj7nxjn2ianm9xhlc0iydzsd0agihi";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

  };

  cpPackage = pkg:
    let
      target = ".spago/${pkg.name}/${pkg.version}";
    in ''
      if [ ! -e ${target} ]; then
        echo "Installing ${target}."
        mkdir -p ${target}
        cp --no-preserve=mode,ownership,timestamp -r ${toString pkg.outPath}/* ${target}
      else
        echo "${target} already exists. Skipping."
      fi
    '';

  getGlob = pkg: ''\".spago/${pkg.name}/${pkg.version}/src/**/*.purs\"'';

  getStoreGlob = pkg: ''\"${pkg.outPath}/src/**/*.purs\"'';

in {
  inherit inputs;

  installSpagoStyle = pkgs.runCommand "install-spago-style" {} ''
      >>$out echo "#!/usr/bin/env bash"
      >>$out echo
      >>$out echo "echo installing dependencies..."
      >>$out echo "${builtins.toString (
        builtins.map cpPackage (builtins.attrValues inputs))}"
      >>$out echo "echo done."
      chmod +x $out
  '';

  buildSpagoStyle = pkgs.runCommand "build-spago-style" {} ''
      >>$out echo "#!/usr/bin/env bash"
      >>$out echo
      >>$out echo "echo building project..."
      >>$out echo "purs compile ${builtins.toString (
        builtins.map getGlob (builtins.attrValues inputs))}" \"\$@\"
      >>$out echo "echo done."
      chmod +x $out
  '';

  buildFromNixStore = pkgs.runCommand "build-from-store" {} ''
      >>$out echo "#!/usr/bin/env bash"
      >>$out echo
      >>$out echo "echo building project using sources from nix store..."
      >>$out echo "purs compile ${builtins.toString (
        builtins.map getStoreGlob (builtins.attrValues inputs))}" \"\$@\"
      >>$out echo "echo done."
      chmod +x $out
  '';

  mkBuildProjectOutput =
    { src, purs }:

    pkgs.stdenv.mkDerivation {
      name = "build-project-output";
      src = src;

      buildInputs = [ purs ];

      installPhase = ''
        mkdir -p $out
        purs compile "$src/**/*.purs" ${builtins.toString
          (builtins.map
            (x: ''"${x.outPath}/src/**/*.purs"'')
            (builtins.attrValues inputs))}
        mv output $out
      '';
    };
}
